services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: o
      MYSQL_USER: esprituser
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  eureka-service:
    image: "${DOCKER_USER:-oumaimakachai}/eureka-server:${IMAGE_TAG:-latest}"
    container_name: eureka-service
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=EurekaServer
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 20s
      timeout: 10s
      retries: 5

  formation-service:
    image: "${DOCKER_USER:-oumaimakachai}/formation-service:${IMAGE_TAG:-latest}"
    container_name: formation-service
    restart: always
    ports:
      - "9094:9094"
    environment:
      - SPRING_APPLICATION_NAME=Formation-Service
      - SERVER_PORT=9094
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/o?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IPADDRESS=true
    depends_on:
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_started

  user-service:
    image: "${DOCKER_USER:-oumaimakachai}/user-service:${IMAGE_TAG:-latest}"
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=Auth
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/o?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=http://localhost:4200
      - SPRING_WEB_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - SPRING_WEB_CORS_ALLOWED_HEADERS=*
      - SPRING_WEB_CORS_ALLOW_CREDENTIALS=true
    depends_on:
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_started

  frontend:
    image: "${DOCKER_USER:-oumaimakachai}/frontend:${IMAGE_TAG:-latest}"
    container_name: frontend
    build:
      context: ../../../frontend/InternshipProject
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - user-service
      - formation-service

volumes:
  mysql-data:
