apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-service
  namespace: esprit-formation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formation-service
  template:
    metadata:
      labels:
        app: formation-service
    spec:
      containers:
        - name: formation-service
          image: oumaimakachai/formation-service:latest
          env:
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/formationdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: formation-service
  namespace: esprit-formation
spec:
  selector:
    app: formation-service
  ports:
    - port: 8082
      targetPort: 8082
